package com.ctms.ctms_backend.payment.entity;

import com.ctms.ctms_backend.budget.entity.CostCategory;
import com.ctms.ctms_backend.esignature.ESignature;
import com.ctms.ctms_backend.site.entity.Site;
import com.ctms.ctms_backend.study.entity.Study;
import com.ctms.ctms_backend.user.User;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.PrePersist;
import jakarta.persistence.PreUpdate;
import jakarta.persistence.Table;
import java.math.BigDecimal;
import java.time.Instant;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

/** BL Epic 8 Story 01/04. Auto-generated by PaymentRuleService/PaymentService when a trigger
 * event fires (visit completion, site activation, FPI/LPI milestone) -- see PaymentService for
 * the call sites. baseAmount/multiplier/capAmount are kept alongside the final `amount` so the
 * calculation stays visible/auditable (CLAUDE.md: "every rule must be inspectable"), not just an
 * opaque final number. Status is linear PENDING -> ON_HOLD -> RELEASED (see PaymentStatus); hold
 * requires a reason, release requires a reason + e-signature (ESignature FK), mirroring Study
 * closeout / Document final-approval's compliance-gated action pattern. */
@Entity
@Table(name = "payment")
@Getter
@Setter
@NoArgsConstructor
public class Payment {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "study_id", nullable = false)
    private Study study;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "site_id")
    private Site site;

    @Enumerated(EnumType.STRING)
    @Column(name = "cost_category", nullable = false, length = 30)
    private CostCategory costCategory;

    @Column(name = "event_code", nullable = false, length = 50)
    private String eventCode;

    @Column(name = "trigger_entity_name", nullable = false, length = 50)
    private String triggerEntityName;

    @Column(name = "trigger_entity_id", nullable = false)
    private Long triggerEntityId;

    @Column(name = "base_amount", nullable = false, precision = 14, scale = 2)
    private BigDecimal baseAmount;

    @Column(nullable = false, precision = 6, scale = 3)
    private BigDecimal multiplier;

    @Column(name = "cap_amount", precision = 14, scale = 2)
    private BigDecimal capAmount;

    @Column(nullable = false, precision = 14, scale = 2)
    private BigDecimal amount;

    @Column(nullable = false, length = 3)
    private String currency;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 20)
    private PaymentStatus status = PaymentStatus.PENDING;

    @Column(name = "hold_reason", length = 500)
    private String holdReason;

    @Column(name = "held_at")
    private Instant heldAt;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "held_by")
    private User heldBy;

    @Column(name = "release_reason", length = 500)
    private String releaseReason;

    @Column(name = "released_at")
    private Instant releasedAt;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "released_by")
    private User releasedBy;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "esignature_id")
    private ESignature eSignature;

    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "created_by", nullable = false)
    private User createdBy;

    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "modified_by", nullable = false)
    private User modifiedBy;

    @Column(name = "modified_at", nullable = false)
    private Instant modifiedAt;

    @PrePersist
    void onCreate() {
        Instant now = Instant.now();
        this.createdAt = now;
        this.modifiedAt = now;
    }

    @PreUpdate
    void onUpdate() {
        this.modifiedAt = Instant.now();
    }
}
